// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAppnVAsqv89BAJ_t8qJk2IGvxAZltGU7s',
    appId: '1:1022849629642:web:870111636f4b7990702333',
    messagingSenderId: '1022849629642',
    projectId: 'aeroride-002',
    authDomain: 'aeroride-002.firebaseapp.com',
    storageBucket: 'aeroride-002.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvW-YOJPfZuXn19Ak97az7T8fh0tXh540',
    appId: '1:1022849629642:android:f616f9f735d6e5c8702333',
    messagingSenderId: '1022849629642',
    projectId: 'aeroride-002',
    storageBucket: 'aeroride-002.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdHhvRDW26XAudlUL9dN4bsVgTG11rw4w',
    appId: '1:1022849629642:ios:68dde487767d6670702333',
    messagingSenderId: '1022849629642',
    projectId: 'aeroride-002',
    storageBucket: 'aeroride-002.firebasestorage.app',
    iosBundleId: 'com.example.aeroride',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdHhvRDW26XAudlUL9dN4bsVgTG11rw4w',
    appId: '1:1022849629642:ios:68dde487767d6670702333',
    messagingSenderId: '1022849629642',
    projectId: 'aeroride-002',
    storageBucket: 'aeroride-002.firebasestorage.app',
    iosBundleId: 'com.example.aeroride',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAppnVAsqv89BAJ_t8qJk2IGvxAZltGU7s',
    appId: '1:1022849629642:web:14ec5732b0f53f0c702333',
    messagingSenderId: '1022849629642',
    projectId: 'aeroride-002',
    authDomain: 'aeroride-002.firebaseapp.com',
    storageBucket: 'aeroride-002.firebasestorage.app',
  );
}
