// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvTSJIReXOpASFEbZZuL-ZAwsSqCOmZOQ',
    appId: '1:889517767998:web:eaffecb7f00797daaa806f',
    messagingSenderId: '889517767998',
    projectId: 'aeroride-665af',
    authDomain: 'aeroride-665af.firebaseapp.com',
    storageBucket: 'aeroride-665af.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-cNRzLAmfPV5JP6ymXMSmdTTDOHrzOOE',
    appId: '1:889517767998:android:d8d7dd203cdf4320aa806f',
    messagingSenderId: '889517767998',
    projectId: 'aeroride-665af',
    storageBucket: 'aeroride-665af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrn827u6Ik9_0ajWPQc0BM8u2wO8Vfl4A',
    appId: '1:889517767998:ios:664dcf9ea6842697aa806f',
    messagingSenderId: '889517767998',
    projectId: 'aeroride-665af',
    storageBucket: 'aeroride-665af.firebasestorage.app',
    iosBundleId: 'com.example.aeroride',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrn827u6Ik9_0ajWPQc0BM8u2wO8Vfl4A',
    appId: '1:889517767998:ios:664dcf9ea6842697aa806f',
    messagingSenderId: '889517767998',
    projectId: 'aeroride-665af',
    storageBucket: 'aeroride-665af.firebasestorage.app',
    iosBundleId: 'com.example.aeroride',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvTSJIReXOpASFEbZZuL-ZAwsSqCOmZOQ',
    appId: '1:889517767998:web:947668360bd8b103aa806f',
    messagingSenderId: '889517767998',
    projectId: 'aeroride-665af',
    authDomain: 'aeroride-665af.firebaseapp.com',
    storageBucket: 'aeroride-665af.firebasestorage.app',
  );

}